import Head from 'next/head';
import Avatar from '../components/Avatar';
import Image from 'next/image';
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid';
import { SearchIcon } from '@heroicons/react/outline';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by Anant Duhan" />
        <link
          rel="icon"
          href="https://freepngimg.com/thumb/google/66893-guava-logo-google-plus-suite-png-image-high-quality.png"
        />
      </Head>

      {/* Header */}
      <header className="flex w-full justify-between p-5 text-sm text-gray-700">
        {/* Left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* Right */}
        <div className="flex space-x-4 items-center">
          <p className="link">
            <a href="https://www.gmail.com">Gmail</a>
          </p>
          <p className="link">Images</p>

          {/* Icons */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          {/* Avatar */}
          <Avatar url="https://avatars.githubusercontent.com/u/50514029?v=4" />
        </div>
      </header>

      {/* Body */}
      <form>
        <Image
          src="https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />

        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input type="text" className="flex-grow focus:outline-none" />
          <MicrophoneIcon className="h-5 w-5" />
        </div>
      </form>

      {/* Footer */}
    </div>
  );
}
